SET GLOBAL time_zone = '-6:00';
-- MySQL Script generated by MySQL Workbench
-- Thu Jan 23 10:20:46 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ferreteria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ferreteria` ;

-- -----------------------------------------------------
-- Schema ferreteria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ferreteria` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci ;
USE `ferreteria` ;

-- -----------------------------------------------------
-- Table `ferreteria`.`herramienta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ferreteria`.`herramienta` ;

CREATE TABLE IF NOT EXISTS `ferreteria`.`herramienta` (
  `codigo` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `precio` DOUBLE NULL,
  `medida` VARCHAR(45) NULL,
  `capacidad` INT NULL,
  `cantidadUnidades` INT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ferreteria`.`material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ferreteria`.`material` ;

CREATE TABLE IF NOT EXISTS `ferreteria`.`material` (
  `codigo` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `precio` DOUBLE NULL,
  `medida` VARCHAR(45) NULL,
  `tamano` VARCHAR(45) NULL,
  `pesoKg` DOUBLE NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ferreteria`.`factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ferreteria`.`factura` ;

CREATE TABLE IF NOT EXISTS `ferreteria`.`factura` (
  `numero` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `total` DOUBLE NULL,
  PRIMARY KEY (`numero`),
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ferreteria`.`detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ferreteria`.`detalle` ;

CREATE TABLE IF NOT EXISTS `ferreteria`.`detalle` (
  `secuencia` INT NOT NULL AUTO_INCREMENT,
  `numero_factura` INT NOT NULL,
  `codigo_material` VARCHAR(10) NOT NULL,
  `codigo_herramienta` VARCHAR(10) NOT NULL,
  `precio_total` DOUBLE NULL,
  PRIMARY KEY (`secuencia`, `numero_factura`),
  UNIQUE INDEX `secuencia_UNIQUE` (`secuencia` ASC) VISIBLE,
  INDEX `fk_detalle_factura_idx` (`numero_factura` ASC) VISIBLE,
  INDEX `fk_detalle_material1_idx` (`codigo_material` ASC) VISIBLE,
  INDEX `fk_detalle_herramienta1_idx` (`codigo_herramienta` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_factura`
    FOREIGN KEY (`numero_factura`)
    REFERENCES `ferreteria`.`factura` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_material1`
    FOREIGN KEY (`codigo_material`)
    REFERENCES `ferreteria`.`material` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_herramienta1`
    FOREIGN KEY (`codigo_herramienta`)
    REFERENCES `ferreteria`.`herramienta` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;